gridUrl: http://ondemand.saucelabs.com/wd/hub
rootUrl: http://localhost:8000/
windowSize: 1024x768

httpTimeout: 40000
suitesPerSession: 20
sessionsPerBrowser: 3
retry: 4

browsers:
  firefox-latest:
    desiredCapabilities:
      version: "45.0"
      browserName: firefox
      platform: LINUX

  chrome-latest:
    desiredCapabilities:
      version: "48.0"
      browserName: chrome
      platform: LINUX
      chromeOptions:
        prefs:
          browser:
            # Disable spellchecker
            enable_spellchecking: false

system:
  plugins:
    gemini-saucelabs-info: {}
  debug: false
