gridUrl: http://ondemand.saucelabs.com/wd/hub
rootUrl: http://localhost:8000/
browsers:
  - {name: chrome, version: 33}
  - {name: opera, version: 12}
  - {name: firefox, version: 29}
  - {name: internet explorer, version: 9}
